### ISSUE TITLE
I can't add chavs in the project

### ISSUE THREAD

**Issue by thanhtamns** [stakewalker/hotnews#4]
I can't add "chavs" in the project
Is "chavs " a library you created yourself or where did it come from?

**Comment by stakewalker** [comment]
Hello friend, good to hear from you.

"chavs.py" worked as a key vault at the time, since it was my very first
project and I didn't know much about security.

Since you're interested, I would love to revisit the code and fix it asap.
Just gimme some hours, and let me know if you have any other issue.

Alex

**Comment by thanhtamns** [comment]
Thank you for your reply.
I have imported all the full API and user_id. But the error below always appears.
![image](https://github.com/stakewalker/hotnews/assets/14258304/85814970-6b14-40ea-95f0-e26f7391eeae)

**Comment by thanhtamns** [comment]
Hey Mate,
Can you upload the full version and it will run perfectly?

**Comment by stakewalker** [comment]
I tried to run it here and at first it seemed like a modification in the AdFly authentication process, but actually it rebranded to [Linkertise](https://migrate-adfly.linkvertise.com/).
Also, I noticed [pyshorteners](https://github.com/ellisonleao/pyshorteners) library has been archived since last year. So we will need to find another way to short this URLs.

There's no other version besides that, and some work is needed to make it work properly again.
Feel free to fork the project and suggest modifications, I would appreciate your contributions!

**Comment by thanhtamns** [comment]
Can you please upload all the files needed in the project?
I see that the current code is missing a lot of files like below:
![image](https://github.com/stakewalker/hotnews/assets/14258304/4badebee-c7a4-43bf-b746-eb8c8b55bc3d)
![image](https://github.com/stakewalker/hotnews/assets/14258304/9987dec5-9b11-4f74-8e7a-923600f4637d)
![image](https://github.com/stakewalker/hotnews/assets/14258304/c0d1e18c-ed77-49b1-bd2b-f13a6c958f47)
![image](https://github.com/stakewalker/hotnews/assets/14258304/a1826cf4-529b-488c-a578-cd4397764035)

**Comment by stakewalker** [comment]
Got it. I'll upload everything as soon as I can. Have a good week!
